name: nw-plate
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::fastapi
  - conda-forge::uvicorn
  - conda-forge::pydantic
  - conda-forge::libsqlite
  - conda-forge::Cloudflare
  - conda-forge::httpx
  - conda-forge::sse-starlette
  - pip
  - pip:
    - openai
    - qdrant-client
    - fastembed
